### Get stock data from the catalog
GET http://localhost:4004/catalog/Books

### Submit an order
POST http://localhost:4004/catalog/submitOrder HTTP/1.1
Content-Type: application/json

{
    "book": 1,
    "quantity": 95
}

### Test endpoint to restock books
POST http://localhost:4004/twilioWebhook HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Body=Yes 400&From=%2b49151000000
