### Bestandsabfrage des Katalogs
GET http://localhost:4004/catalog/Books

### Sende eine Bestellung
POST http://localhost:4004/catalog/submitOrder HTTP/1.1
Content-Type: application/json
 
{
   "book": 1,
   "quantity": 95
}

### Teste den Webhook um Bücher nachzubestellen
POST http://localhost:4004/twilioWebhook HTTP/1.1
Content-Type: application/x-www-form-urlencoded
 
Body=Yes 400&From=%2b49151000000
